import type { PluginPermission } from '../../types/plugins'
export const permissionLabels: Record<PluginPermission, string> = {
  'accounts:read': 'Read account names and current selection',
  'quests:read': 'Read quests for selected accounts (authenticated)',
  'settings:read': 'Read game path and launcher connection settings',
  'inventory:read': 'Read inventory for selected accounts (authenticated)',
  'inventory:recycle': 'Request permanent item recycling with Penny confirmation',
  'epic-launcher:close': 'Force-close Epic Games Launcher on Windows',
  'system:read': 'Read OS version, architecture, memory totals, and uptime',
  'displays:read': 'Read monitor sizes and scaling (no screenshots)',
  'power:read': 'Read whether the computer is using battery power',
  'fortnite:profiles': 'Read Fortnite game profiles for selected accounts (account secrets and purchase history removed)',
  'fortnite:commands': 'Run the declared Fortnite commands below on selected accounts',
  'fortnite:sessions': 'See which match selected accounts are in',
  'fortnite:presence': 'Start, change and stop the friend-facing Fortnite status for selected accounts',
  'eos:locker:read': 'Read selected accounts’ equipped EOS locker slots',
  storage: 'Save data in this add-on’s JSON store',
  navigation: 'Navigate to Penny pages',
  notifications: 'Show desktop notifications',
  'external-links': 'Open HTTPS links in your browser',
  ui: 'Add panels, actions, and settings to its add-on card',
}
