/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as PluginsRouteImport } from './routes/plugins/route'
import { Route as AccountRouteImport } from './routes/account/route'
import { Route as IndexImport } from './routes/index'
import { Route as StwOperationsXpboostsRouteImport } from './routes/stw-operations/xpboosts/route'
import { Route as StwOperationsUrnsRouteImport } from './routes/stw-operations/urns/route'
import { Route as StwOperationsTimelineRouteImport } from './routes/stw-operations/timeline/route'
import { Route as StwOperationsTaxiServiceRouteImport } from './routes/stw-operations/taxi-service/route'
import { Route as StwOperationsSquadsRouteImport } from './routes/stw-operations/squads/route'
import { Route as StwOperationsShopRouteImport } from './routes/stw-operations/shop/route'
import { Route as StwOperationsQuestsRouteImport } from './routes/stw-operations/quests/route'
import { Route as StwOperationsPartyRouteImport } from './routes/stw-operations/party/route'
import { Route as StwOperationsOutpostRouteImport } from './routes/stw-operations/outpost/route'
import { Route as StwOperationsLoadoutsRouteImport } from './routes/stw-operations/loadouts/route'
import { Route as StwOperationsLeaderboardsRouteImport } from './routes/stw-operations/leaderboards/route'
import { Route as StwOperationsInventoryRouteImport } from './routes/stw-operations/inventory/route'
import { Route as StwOperationsExpeditionsRouteImport } from './routes/stw-operations/expeditions/route'
import { Route as StwOperationsEnduranceRouteImport } from './routes/stw-operations/endurance/route'
import { Route as StwOperationsCompendiumRouteImport } from './routes/stw-operations/compendium/route'
import { Route as StwOperationsAutomationRouteImport } from './routes/stw-operations/automation/route'
import { Route as StwOperationsAutoLlamasRouteImport } from './routes/stw-operations/auto-llamas/route'
import { Route as InformationCreditsRouteImport } from './routes/information/credits/route'
import { Route as AdvancedModeWorldInfoRouteImport } from './routes/advanced-mode/world-info/route'
import { Route as AdvancedModeServerStatusRouteImport } from './routes/advanced-mode/server-status/route'
import { Route as AdvancedModeMatchmakingTrackRouteImport } from './routes/advanced-mode/matchmaking-track/route'
import { Route as AdvancedModeGameSettingsRouteImport } from './routes/advanced-mode/game-settings/route'
import { Route as AccountsRemoveRouteImport } from './routes/accounts/remove/route'
import { Route as AccountManagementVbucksInformationRouteImport } from './routes/account-management/vbucks-information/route'
import { Route as AccountManagementRedeemCodesRouteImport } from './routes/account-management/redeem-codes/route'
import { Route as AccountManagementProfileRouteImport } from './routes/account-management/profile/route'
import { Route as AccountManagementLockerRouteImport } from './routes/account-management/locker/route'
import { Route as AccountManagementGiftsInformationRouteImport } from './routes/account-management/gifts-information/route'
import { Route as AccountManagementFriendsRouteImport } from './routes/account-management/friends/route'
import { Route as AccountManagementEulaRouteImport } from './routes/account-management/eula/route'
import { Route as AccountManagementEpicGamesSettingsRouteImport } from './routes/account-management/epic-games-settings/route'
import { Route as AccountsAddTypeImport } from './routes/accounts/add/$type'

// Create/Update Routes

const SettingsRouteRoute = SettingsRouteImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const PluginsRouteRoute = PluginsRouteImport.update({
  path: '/plugins',
  getParentRoute: () => rootRoute,
} as any)

const AccountRouteRoute = AccountRouteImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StwOperationsXpboostsRouteRoute = StwOperationsXpboostsRouteImport.update(
  {
    path: '/stw-operations/xpboosts',
    getParentRoute: () => rootRoute,
  } as any,
)

const StwOperationsUrnsRouteRoute = StwOperationsUrnsRouteImport.update({
  path: '/stw-operations/urns',
  getParentRoute: () => rootRoute,
} as any)

const StwOperationsTimelineRouteRoute = StwOperationsTimelineRouteImport.update(
  {
    path: '/stw-operations/timeline',
    getParentRoute: () => rootRoute,
  } as any,
)

const StwOperationsTaxiServiceRouteRoute =
  StwOperationsTaxiServiceRouteImport.update({
    path: '/stw-operations/taxi-service',
    getParentRoute: () => rootRoute,
  } as any)

const StwOperationsSquadsRouteRoute = StwOperationsSquadsRouteImport.update({
  path: '/stw-operations/squads',
  getParentRoute: () => rootRoute,
} as any)

const StwOperationsShopRouteRoute = StwOperationsShopRouteImport.update({
  path: '/stw-operations/shop',
  getParentRoute: () => rootRoute,
} as any)

const StwOperationsQuestsRouteRoute = StwOperationsQuestsRouteImport.update({
  path: '/stw-operations/quests',
  getParentRoute: () => rootRoute,
} as any)

const StwOperationsPartyRouteRoute = StwOperationsPartyRouteImport.update({
  path: '/stw-operations/party',
  getParentRoute: () => rootRoute,
} as any)

const StwOperationsOutpostRouteRoute = StwOperationsOutpostRouteImport.update({
  path: '/stw-operations/outpost',
  getParentRoute: () => rootRoute,
} as any)

const StwOperationsLoadoutsRouteRoute = StwOperationsLoadoutsRouteImport.update(
  {
    path: '/stw-operations/loadouts',
    getParentRoute: () => rootRoute,
  } as any,
)

const StwOperationsLeaderboardsRouteRoute =
  StwOperationsLeaderboardsRouteImport.update({
    path: '/stw-operations/leaderboards',
    getParentRoute: () => rootRoute,
  } as any)

const StwOperationsInventoryRouteRoute =
  StwOperationsInventoryRouteImport.update({
    path: '/stw-operations/inventory',
    getParentRoute: () => rootRoute,
  } as any)

const StwOperationsExpeditionsRouteRoute =
  StwOperationsExpeditionsRouteImport.update({
    path: '/stw-operations/expeditions',
    getParentRoute: () => rootRoute,
  } as any)

const StwOperationsEnduranceRouteRoute =
  StwOperationsEnduranceRouteImport.update({
    path: '/stw-operations/endurance',
    getParentRoute: () => rootRoute,
  } as any)

const StwOperationsCompendiumRouteRoute =
  StwOperationsCompendiumRouteImport.update({
    path: '/stw-operations/compendium',
    getParentRoute: () => rootRoute,
  } as any)

const StwOperationsAutomationRouteRoute =
  StwOperationsAutomationRouteImport.update({
    path: '/stw-operations/automation',
    getParentRoute: () => rootRoute,
  } as any)

const StwOperationsAutoLlamasRouteRoute =
  StwOperationsAutoLlamasRouteImport.update({
    path: '/stw-operations/auto-llamas',
    getParentRoute: () => rootRoute,
  } as any)

const InformationCreditsRouteRoute = InformationCreditsRouteImport.update({
  path: '/information/credits',
  getParentRoute: () => rootRoute,
} as any)

const AdvancedModeWorldInfoRouteRoute = AdvancedModeWorldInfoRouteImport.update(
  {
    path: '/advanced-mode/world-info',
    getParentRoute: () => rootRoute,
  } as any,
)

const AdvancedModeServerStatusRouteRoute =
  AdvancedModeServerStatusRouteImport.update({
    path: '/advanced-mode/server-status',
    getParentRoute: () => rootRoute,
  } as any)

const AdvancedModeMatchmakingTrackRouteRoute =
  AdvancedModeMatchmakingTrackRouteImport.update({
    path: '/advanced-mode/matchmaking-track',
    getParentRoute: () => rootRoute,
  } as any)

const AdvancedModeGameSettingsRouteRoute =
  AdvancedModeGameSettingsRouteImport.update({
    path: '/advanced-mode/game-settings',
    getParentRoute: () => rootRoute,
  } as any)

const AccountsRemoveRouteRoute = AccountsRemoveRouteImport.update({
  path: '/accounts/remove',
  getParentRoute: () => rootRoute,
} as any)

const AccountManagementVbucksInformationRouteRoute =
  AccountManagementVbucksInformationRouteImport.update({
    path: '/account-management/vbucks-information',
    getParentRoute: () => rootRoute,
  } as any)

const AccountManagementRedeemCodesRouteRoute =
  AccountManagementRedeemCodesRouteImport.update({
    path: '/account-management/redeem-codes',
    getParentRoute: () => rootRoute,
  } as any)

const AccountManagementProfileRouteRoute =
  AccountManagementProfileRouteImport.update({
    path: '/account-management/profile',
    getParentRoute: () => rootRoute,
  } as any)

const AccountManagementLockerRouteRoute =
  AccountManagementLockerRouteImport.update({
    path: '/account-management/locker',
    getParentRoute: () => rootRoute,
  } as any)

const AccountManagementGiftsInformationRouteRoute =
  AccountManagementGiftsInformationRouteImport.update({
    path: '/account-management/gifts-information',
    getParentRoute: () => rootRoute,
  } as any)

const AccountManagementFriendsRouteRoute =
  AccountManagementFriendsRouteImport.update({
    path: '/account-management/friends',
    getParentRoute: () => rootRoute,
  } as any)

const AccountManagementEulaRouteRoute = AccountManagementEulaRouteImport.update(
  {
    path: '/account-management/eula',
    getParentRoute: () => rootRoute,
  } as any,
)

const AccountManagementEpicGamesSettingsRouteRoute =
  AccountManagementEpicGamesSettingsRouteImport.update({
    path: '/account-management/epic-games-settings',
    getParentRoute: () => rootRoute,
  } as any)

const AccountsAddTypeRoute = AccountsAddTypeImport.update({
  path: '/accounts/add/$type',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRoute
    }
    '/plugins': {
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/epic-games-settings': {
      preLoaderRoute: typeof AccountManagementEpicGamesSettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/eula': {
      preLoaderRoute: typeof AccountManagementEulaRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/friends': {
      preLoaderRoute: typeof AccountManagementFriendsRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/gifts-information': {
      preLoaderRoute: typeof AccountManagementGiftsInformationRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/locker': {
      preLoaderRoute: typeof AccountManagementLockerRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/profile': {
      preLoaderRoute: typeof AccountManagementProfileRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/redeem-codes': {
      preLoaderRoute: typeof AccountManagementRedeemCodesRouteImport
      parentRoute: typeof rootRoute
    }
    '/account-management/vbucks-information': {
      preLoaderRoute: typeof AccountManagementVbucksInformationRouteImport
      parentRoute: typeof rootRoute
    }
    '/accounts/remove': {
      preLoaderRoute: typeof AccountsRemoveRouteImport
      parentRoute: typeof rootRoute
    }
    '/advanced-mode/game-settings': {
      preLoaderRoute: typeof AdvancedModeGameSettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/advanced-mode/matchmaking-track': {
      preLoaderRoute: typeof AdvancedModeMatchmakingTrackRouteImport
      parentRoute: typeof rootRoute
    }
    '/advanced-mode/server-status': {
      preLoaderRoute: typeof AdvancedModeServerStatusRouteImport
      parentRoute: typeof rootRoute
    }
    '/advanced-mode/world-info': {
      preLoaderRoute: typeof AdvancedModeWorldInfoRouteImport
      parentRoute: typeof rootRoute
    }
    '/information/credits': {
      preLoaderRoute: typeof InformationCreditsRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/auto-llamas': {
      preLoaderRoute: typeof StwOperationsAutoLlamasRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/automation': {
      preLoaderRoute: typeof StwOperationsAutomationRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/compendium': {
      preLoaderRoute: typeof StwOperationsCompendiumRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/endurance': {
      preLoaderRoute: typeof StwOperationsEnduranceRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/expeditions': {
      preLoaderRoute: typeof StwOperationsExpeditionsRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/inventory': {
      preLoaderRoute: typeof StwOperationsInventoryRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/leaderboards': {
      preLoaderRoute: typeof StwOperationsLeaderboardsRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/loadouts': {
      preLoaderRoute: typeof StwOperationsLoadoutsRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/outpost': {
      preLoaderRoute: typeof StwOperationsOutpostRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/party': {
      preLoaderRoute: typeof StwOperationsPartyRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/quests': {
      preLoaderRoute: typeof StwOperationsQuestsRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/shop': {
      preLoaderRoute: typeof StwOperationsShopRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/squads': {
      preLoaderRoute: typeof StwOperationsSquadsRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/taxi-service': {
      preLoaderRoute: typeof StwOperationsTaxiServiceRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/timeline': {
      preLoaderRoute: typeof StwOperationsTimelineRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/urns': {
      preLoaderRoute: typeof StwOperationsUrnsRouteImport
      parentRoute: typeof rootRoute
    }
    '/stw-operations/xpboosts': {
      preLoaderRoute: typeof StwOperationsXpboostsRouteImport
      parentRoute: typeof rootRoute
    }
    '/accounts/add/$type': {
      preLoaderRoute: typeof AccountsAddTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AccountRouteRoute,
  PluginsRouteRoute,
  SettingsRouteRoute,
  AccountManagementEpicGamesSettingsRouteRoute,
  AccountManagementEulaRouteRoute,
  AccountManagementFriendsRouteRoute,
  AccountManagementGiftsInformationRouteRoute,
  AccountManagementLockerRouteRoute,
  AccountManagementProfileRouteRoute,
  AccountManagementRedeemCodesRouteRoute,
  AccountManagementVbucksInformationRouteRoute,
  AccountsRemoveRouteRoute,
  AdvancedModeGameSettingsRouteRoute,
  AdvancedModeMatchmakingTrackRouteRoute,
  AdvancedModeServerStatusRouteRoute,
  AdvancedModeWorldInfoRouteRoute,
  InformationCreditsRouteRoute,
  StwOperationsAutoLlamasRouteRoute,
  StwOperationsAutomationRouteRoute,
  StwOperationsCompendiumRouteRoute,
  StwOperationsEnduranceRouteRoute,
  StwOperationsExpeditionsRouteRoute,
  StwOperationsInventoryRouteRoute,
  StwOperationsLeaderboardsRouteRoute,
  StwOperationsLoadoutsRouteRoute,
  StwOperationsOutpostRouteRoute,
  StwOperationsPartyRouteRoute,
  StwOperationsQuestsRouteRoute,
  StwOperationsShopRouteRoute,
  StwOperationsSquadsRouteRoute,
  StwOperationsTaxiServiceRouteRoute,
  StwOperationsTimelineRouteRoute,
  StwOperationsUrnsRouteRoute,
  StwOperationsXpboostsRouteRoute,
  AccountsAddTypeRoute,
])

/* prettier-ignore-end */
